#!/usr/bin/env bash
# Auto-generate one category listing page per post sub-folder.
#
# Tola has no dynamic routes: every URL needs a content file, and link
# validation is error-level. So for each folder `content/posts/<cat>/` we
# (re)write a stub `content/categories/<cat>.typ` that renders that category,
# and delete stubs whose folder no longer exists. Idempotent — safe to re-run.
#
# Runs automatically in build.sh (deploy). Run it locally after adding or
# removing a category folder:  bash scripts/gen-categories.sh
set -euo pipefail

cd "$(dirname "$0")/.."          # repo root
POSTS_DIR="content/posts"
CAT_DIR="content/categories"
mkdir -p "$CAT_DIR"

wanted=" "                        # space-delimited set of live category names

for d in "$POSTS_DIR"/*/; do
  [ -d "$d" ] || continue         # only sub-folders are categories
  name="$(basename "$d")"
  wanted="$wanted$name "
  cat > "$CAT_DIR/$name.typ" <<EOF
// AUTO-GENERATED by scripts/gen-categories.sh — do not edit.
// Add/remove a folder under content/posts/ and re-run the script instead.
#import "/templates/category.typ": category
#show: category.with(category: "$name", title: "Category: $name")
EOF
  echo "  categories/$name.typ"
done

# Remove stale stubs (folder gone), but never the hand-written index.
for f in "$CAT_DIR"/*.typ; do
  [ -e "$f" ] || continue
  base="$(basename "$f" .typ)"
  [ "$base" = "index" ] && continue
  case "$wanted" in
    *" $base "*) : ;;
    *) rm "$f"; echo "  removed stale categories/$base.typ" ;;
  esac
done
