// AUTO-GENERATED by scripts/gen-categories.sh — do not edit.
// Add/remove a folder under content/posts/ and re-run the script instead.
#import "/templates/category.typ": category
#show: category.with(category: "rust", title: "Category: rust")
